all: true
with-expecter: true
recursive: true
keeptree: true
packages:
  github.com/radityacandra/banking-challenge:
    config:
      dir: mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_" }}
