// Code generated by mockery v2.52.4. DO NOT EDIT.

package repository

import (
	context "context"

	model "github.com/radityacandra/banking-challenge/internal/application/user/model"
	mock "github.com/stretchr/testify/mock"
)

// MockIRepository is an autogenerated mock type for the IRepository type
type MockIRepository struct {
	mock.Mock
}

type MockIRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRepository) EXPECT() *MockIRepository_Expecter {
	return &MockIRepository_Expecter{mock: &_m.Mock}
}

// InsertUser provides a mock function with given fields: ctx, user
func (_m *MockIRepository) InsertUser(ctx context.Context, user model.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for InsertUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIRepository_InsertUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertUser'
type MockIRepository_InsertUser_Call struct {
	*mock.Call
}

// InsertUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user model.User
func (_e *MockIRepository_Expecter) InsertUser(ctx interface{}, user interface{}) *MockIRepository_InsertUser_Call {
	return &MockIRepository_InsertUser_Call{Call: _e.mock.On("InsertUser", ctx, user)}
}

func (_c *MockIRepository_InsertUser_Call) Run(run func(ctx context.Context, user model.User)) *MockIRepository_InsertUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.User))
	})
	return _c
}

func (_c *MockIRepository_InsertUser_Call) Return(_a0 error) *MockIRepository_InsertUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIRepository_InsertUser_Call) RunAndReturn(run func(context.Context, model.User) error) *MockIRepository_InsertUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIRepository creates a new instance of MockIRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRepository {
	mock := &MockIRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
