// Code generated by mockery v2.52.4. DO NOT EDIT.

package service

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	types "github.com/radityacandra/banking-challenge/internal/application/user/types"
)

// MockIService is an autogenerated mock type for the IService type
type MockIService struct {
	mock.Mock
}

type MockIService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIService) EXPECT() *MockIService_Expecter {
	return &MockIService_Expecter{mock: &_m.Mock}
}

// RegisterUser provides a mock function with given fields: ctx, input
func (_m *MockIService) RegisterUser(ctx context.Context, input types.RegisterUserInput) (types.RegisterUserOutput, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 types.RegisterUserOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.RegisterUserInput) (types.RegisterUserOutput, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.RegisterUserInput) types.RegisterUserOutput); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(types.RegisterUserOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.RegisterUserInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_RegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUser'
type MockIService_RegisterUser_Call struct {
	*mock.Call
}

// RegisterUser is a helper method to define mock.On call
//   - ctx context.Context
//   - input types.RegisterUserInput
func (_e *MockIService_Expecter) RegisterUser(ctx interface{}, input interface{}) *MockIService_RegisterUser_Call {
	return &MockIService_RegisterUser_Call{Call: _e.mock.On("RegisterUser", ctx, input)}
}

func (_c *MockIService_RegisterUser_Call) Run(run func(ctx context.Context, input types.RegisterUserInput)) *MockIService_RegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.RegisterUserInput))
	})
	return _c
}

func (_c *MockIService_RegisterUser_Call) Return(_a0 types.RegisterUserOutput, _a1 error) *MockIService_RegisterUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_RegisterUser_Call) RunAndReturn(run func(context.Context, types.RegisterUserInput) (types.RegisterUserOutput, error)) *MockIService_RegisterUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIService creates a new instance of MockIService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIService {
	mock := &MockIService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
