// Code generated by mockery v2.52.4. DO NOT EDIT.

package service

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	types "github.com/radityacandra/banking-challenge/internal/application/user-account/types"
)

// MockIService is an autogenerated mock type for the IService type
type MockIService struct {
	mock.Mock
}

type MockIService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIService) EXPECT() *MockIService_Expecter {
	return &MockIService_Expecter{mock: &_m.Mock}
}

// GetBalance provides a mock function with given fields: ctx, accountNo
func (_m *MockIService) GetBalance(ctx context.Context, accountNo string) (types.GetBalanceOutput, error) {
	ret := _m.Called(ctx, accountNo)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 types.GetBalanceOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (types.GetBalanceOutput, error)); ok {
		return rf(ctx, accountNo)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) types.GetBalanceOutput); ok {
		r0 = rf(ctx, accountNo)
	} else {
		r0 = ret.Get(0).(types.GetBalanceOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountNo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type MockIService_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - accountNo string
func (_e *MockIService_Expecter) GetBalance(ctx interface{}, accountNo interface{}) *MockIService_GetBalance_Call {
	return &MockIService_GetBalance_Call{Call: _e.mock.On("GetBalance", ctx, accountNo)}
}

func (_c *MockIService_GetBalance_Call) Run(run func(ctx context.Context, accountNo string)) *MockIService_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIService_GetBalance_Call) Return(_a0 types.GetBalanceOutput, _a1 error) *MockIService_GetBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_GetBalance_Call) RunAndReturn(run func(context.Context, string) (types.GetBalanceOutput, error)) *MockIService_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// StoreCash provides a mock function with given fields: ctx, input
func (_m *MockIService) StoreCash(ctx context.Context, input types.TransactionInput) (types.GetBalanceOutput, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for StoreCash")
	}

	var r0 types.GetBalanceOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.TransactionInput) (types.GetBalanceOutput, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.TransactionInput) types.GetBalanceOutput); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(types.GetBalanceOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.TransactionInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_StoreCash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreCash'
type MockIService_StoreCash_Call struct {
	*mock.Call
}

// StoreCash is a helper method to define mock.On call
//   - ctx context.Context
//   - input types.TransactionInput
func (_e *MockIService_Expecter) StoreCash(ctx interface{}, input interface{}) *MockIService_StoreCash_Call {
	return &MockIService_StoreCash_Call{Call: _e.mock.On("StoreCash", ctx, input)}
}

func (_c *MockIService_StoreCash_Call) Run(run func(ctx context.Context, input types.TransactionInput)) *MockIService_StoreCash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.TransactionInput))
	})
	return _c
}

func (_c *MockIService_StoreCash_Call) Return(_a0 types.GetBalanceOutput, _a1 error) *MockIService_StoreCash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_StoreCash_Call) RunAndReturn(run func(context.Context, types.TransactionInput) (types.GetBalanceOutput, error)) *MockIService_StoreCash_Call {
	_c.Call.Return(run)
	return _c
}

// WithdrawCash provides a mock function with given fields: ctx, input
func (_m *MockIService) WithdrawCash(ctx context.Context, input types.TransactionInput) (types.GetBalanceOutput, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for WithdrawCash")
	}

	var r0 types.GetBalanceOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.TransactionInput) (types.GetBalanceOutput, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.TransactionInput) types.GetBalanceOutput); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(types.GetBalanceOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.TransactionInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_WithdrawCash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithdrawCash'
type MockIService_WithdrawCash_Call struct {
	*mock.Call
}

// WithdrawCash is a helper method to define mock.On call
//   - ctx context.Context
//   - input types.TransactionInput
func (_e *MockIService_Expecter) WithdrawCash(ctx interface{}, input interface{}) *MockIService_WithdrawCash_Call {
	return &MockIService_WithdrawCash_Call{Call: _e.mock.On("WithdrawCash", ctx, input)}
}

func (_c *MockIService_WithdrawCash_Call) Run(run func(ctx context.Context, input types.TransactionInput)) *MockIService_WithdrawCash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.TransactionInput))
	})
	return _c
}

func (_c *MockIService_WithdrawCash_Call) Return(_a0 types.GetBalanceOutput, _a1 error) *MockIService_WithdrawCash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_WithdrawCash_Call) RunAndReturn(run func(context.Context, types.TransactionInput) (types.GetBalanceOutput, error)) *MockIService_WithdrawCash_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIService creates a new instance of MockIService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIService {
	mock := &MockIService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
