// Code generated by mockery v2.52.4. DO NOT EDIT.

package model

import mock "github.com/stretchr/testify/mock"

// MockUserAccount is an autogenerated mock type for the UserAccount type
type MockUserAccount struct {
	mock.Mock
}

type MockUserAccount_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserAccount) EXPECT() *MockUserAccount_Expecter {
	return &MockUserAccount_Expecter{mock: &_m.Mock}
}

// NewMockUserAccount creates a new instance of MockUserAccount. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserAccount(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserAccount {
	mock := &MockUserAccount{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
